language: python
jdk: openjdk11
sudo: false
python:
  - '3.6'
install:
  - pip install cython
  - pip install -r requirements-dev.txt
script:
  - make ci-test
deploy:
    provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
        repo: dlt-rilmta/purepospy
        branch: master
        tags: true
    notifications:
        email: false
